version: "3"
services:
  iptv-proxyhafen:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # If your are using local m3u file instead of m3u remote file
      # put your m3u file in this folder
      - /mnt/iptv-proxy/config:/root/iptv
    container_name: "iptv-proxy-hafen-v2"
    restart: on-failure
    ports:
       # have to be the same as ENV variable PORT
      - 9082:8082
    labels:
      - "com.centurylabs.watchtower.enable=false"
    environment:
      # if you are using m3u remote file
      M3U_URL: http://hfpremium.com:80/get.php?username=23469931&password=j5wFYuQ&type=m3u_plus&output=ts
      #M3U_URL: /root/iptv/iptv.m3u
      # Port to expose the IPTVs endpoints
      PORT: 8082
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: tvh.it-moebius.de
      GIN_MODE: release
      DEBUG_LOGGING: true
      ERROR_DETAIL_LEVEL: full
      ## Xtream-code proxy configuration
      XTREAM_USER: 23469931
      XTREAM_PASSWORD: j5wFYuQ
      XTREAM_BASE_URL: "http://hfpremium.com:80"
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: 23469931
      PASSWORD: j5wFYuQ

